/**
 * sync-config.js — Generate masterConfig.js from config.yaml
 *
 * Reads config.yaml (the single source of truth for branding, theme, scanning,
 * snippets, and timeouts) and writes configuration/masterConfig.js.
 *
 * The botpress and defaultBotTheme sections are JS-only and preserved here.
 *
 * Run: node scripts/sync-config.js
 * Runs automatically via "prebuild" in package.json.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const YAML_PATH = path.join(__dirname, '..', 'config.yaml');
const OUTPUT_PATH = path.join(__dirname, '..', 'configuration', 'masterConfig.js');

// Read and parse YAML
const yamlContent = fs.readFileSync(YAML_PATH, 'utf8');
const config = yaml.load(yamlContent);

// Helper: format a JS value with proper indentation
function toJS(value, indent = 2) {
    const pad = ' '.repeat(indent);
    if (typeof value === 'string') return `"${value}"`;
    if (typeof value === 'number' || typeof value === 'boolean') return String(value);
    if (Array.isArray(value)) {
        if (value.length === 0) return '[]';
        // Check if array of objects or primitives
        if (typeof value[0] === 'object') {
            const items = value.map(item => {
                const entries = Object.entries(item)
                    .map(([k, v]) => `${k}: ${toJS(v)}`)
                    .join(', ');
                return `${pad}    { ${entries} }`;
            });
            return `[\n${items.join(',\n')}\n${pad}]`;
        }
        const items = value.map(v => `${pad}    ${toJS(v)}`);
        return `[\n${items.join(',\n')}\n${pad}]`;
    }
    if (typeof value === 'object' && value !== null) {
        const entries = Object.entries(value).map(([k, v]) => {
            return `${pad}    ${k}: ${toJS(v, indent + 4)}`;
        });
        return `{\n${entries.join(',\n')}\n${pad}}`;
    }
    return String(value);
}

// Build section strings
function buildSection(name, obj, indent = 4) {
    const pad = ' '.repeat(indent);
    const entries = Object.entries(obj).map(([key, value]) => {
        return `${pad}    ${key}: ${toJS(value, indent + 4)},`;
    });
    return `${pad}${name}: {\n${entries.join('\n')}\n${pad}},`;
}

// Generate the output
const output = `// =============================================================================
// MASTER CONFIGURATION (Client-Side)
// =============================================================================
// AUTO-GENERATED from config.yaml by scripts/sync-config.js
// Do NOT edit this file directly — edit config.yaml instead.
//
// Regenerate: node scripts/sync-config.js
// =============================================================================

export const CONFIG = {

    // -------------------------------------------------------------------------
    // Branding (from config.yaml)
    // -------------------------------------------------------------------------
${buildSection('branding', config.branding)}

    // -------------------------------------------------------------------------
    // Theme Colors (from config.yaml)
    // -------------------------------------------------------------------------
${buildSection('theme', config.theme)}

    // -------------------------------------------------------------------------
    // Scanning Stage (from config.yaml)
    // -------------------------------------------------------------------------
${buildSection('scanningStage', config.scanningStage)}

    // -------------------------------------------------------------------------
    // Snippets (from config.yaml)
    // -------------------------------------------------------------------------
${buildSection('snippets', config.snippets)}

    // -------------------------------------------------------------------------
    // Timeouts & Limits (from config.yaml)
    // -------------------------------------------------------------------------
${buildSection('timeouts', config.timeouts)}

    // -------------------------------------------------------------------------
    // Botpress Configuration (JS-only — not in config.yaml)
    // -------------------------------------------------------------------------
    botpress: {
        botId: process.env.NEXT_PUBLIC_BOTPRESS_BOT_ID || '3809961f-f802-40a3-aa5a-9eb91c0dedbb',
        clientId: process.env.NEXT_PUBLIC_BOTPRESS_CLIENT_ID || 'f4011114-6902-416b-b164-12a8df8d0f3d',
    },

    // -------------------------------------------------------------------------
    // Default Bot Theme (JS-only — Marv fallback)
    // -------------------------------------------------------------------------
    defaultBotTheme: {
        name: 'Marv',
        avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=marv&backgroundColor=b6e3f4&eyes=happy&mouth=smile01',
        primaryColor: '#2563eb',
        secondaryColor: '#1e40af',
        description: 'Your friendly assistant'
    },
};
`;

fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
console.log(`[sync-config] Generated ${OUTPUT_PATH} from ${YAML_PATH}`);
