// =============================================================================
// MASTER CONFIGURATION (Client-Side)
// =============================================================================
// AUTO-GENERATED from config.yaml by scripts/sync-config.js
// Do NOT edit this file directly — edit config.yaml instead.
//
// Regenerate: node scripts/sync-config.js
// =============================================================================

export const CONFIG = {

    // -------------------------------------------------------------------------
    // Branding (from config.yaml)
    // -------------------------------------------------------------------------
    branding: {
        companyName: "Member Solutions",
        poweredByText: "Powered by Member Solutions",
        copyright: "Copyright © 2025 Member Solutions",
        legalLinks: "Privacy Policy  |  Terms of Service",
        loadingAnimationPath: "/images/megaman.gif",
        websiteUrl: "https://membersolutions.com",
        emailFrom: "Magic Page <noreply@membies.com>",
    },

    // -------------------------------------------------------------------------
    // Theme Colors (from config.yaml)
    // -------------------------------------------------------------------------
    theme: {
        primaryColor: "#1863DC",
        secondaryColor: "#00234C",
        accentColor: "#F48D03",
        gradientStart: "#00234C",
        gradientMid: "#1863DC",
        gradientEnd: "#F48D03",
        textPrimary: "#212121",
        textSecondary: "#858585",
        textLight: "#FFFFFF",
        backgroundPrimary: "#FFFFFF",
        backgroundSecondary: "#F4F4F4",
        backgroundDark: "#00234C",
        buttonPrimary: "#1863DC",
        buttonPrimaryHover: "#1454B8",
        buttonSecondary: "#F48D03",
        buttonSecondaryHover: "#D97A03",
        borderLight: "#EBEBEB",
        borderMedium: "#CCCCCC",
    },

    // -------------------------------------------------------------------------
    // Scanning Stage (from config.yaml)
    // -------------------------------------------------------------------------
    scanningStage: {
        quoteDelayMs: 5000,
        quotes: [
            "Building Your AI",
            "Skimming Your Website",
            "Loading All The Goodies!",
            "Very Interesting!",
            "Almost There...",
            "Crunching The Data"
        ],
        steps: [
            { name: "Loading website", duration: 2000 },
            { name: "Scanning website", duration: 3000 },
            { name: "Generating AI Agent", duration: 4000 },
            { name: "Build preview", duration: 5000 }
        ],
    },

    // -------------------------------------------------------------------------
    // Snippets (from config.yaml)
    // -------------------------------------------------------------------------
    snippets: {
        displayTimeMs: 3000,
    },

    // -------------------------------------------------------------------------
    // Timeouts & Limits (from config.yaml)
    // -------------------------------------------------------------------------
    timeouts: {
        scrapeStaleMs: 600000,
    },

    // -------------------------------------------------------------------------
    // Botpress Configuration (JS-only — not in config.yaml)
    // -------------------------------------------------------------------------
    botpress: {
        botId: process.env.NEXT_PUBLIC_BOTPRESS_BOT_ID || '3809961f-f802-40a3-aa5a-9eb91c0dedbb',
        clientId: process.env.NEXT_PUBLIC_BOTPRESS_CLIENT_ID || 'f4011114-6902-416b-b164-12a8df8d0f3d',
    },

    // -------------------------------------------------------------------------
    // Default Bot Theme (JS-only — Marv fallback)
    // -------------------------------------------------------------------------
    defaultBotTheme: {
        name: 'Marv',
        avatar: 'https://api.dicebear.com/7.x/bottts-neutral/svg?seed=marv&backgroundColor=b6e3f4&eyes=happy&mouth=smile01',
        primaryColor: '#2563eb',
        secondaryColor: '#1e40af',
        description: 'Your friendly assistant'
    },
};
